// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrvgMM9wNPizVxLrnN2b7_F_Qq5mZgA8',
    appId: '1:911760582251:web:8433995f87c3055d5ff32e',
    messagingSenderId: '911760582251',
    projectId: 'noteapps-9527f',
    authDomain: 'noteapps-9527f.firebaseapp.com',
    storageBucket: 'noteapps-9527f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTMqf5zzT8u0V44dkxr20FAhCLx7ti1Y',
    appId: '1:911760582251:android:bed718ca04bed7395ff32e',
    messagingSenderId: '911760582251',
    projectId: 'noteapps-9527f',
    storageBucket: 'noteapps-9527f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGrvgMM9wNPizVxLrnN2b7_F_Qq5mZgA8',
    appId: '1:911760582251:web:8fe4e66f14205d575ff32e',
    messagingSenderId: '911760582251',
    projectId: 'noteapps-9527f',
    authDomain: 'noteapps-9527f.firebaseapp.com',
    storageBucket: 'noteapps-9527f.firebasestorage.app',
  );
}
